### ISSUE TITLE
TypeError: Cannot read property '__MIDDLEWARES__' of undefined

### ISSUE THREAD

**Issue by xiajinchun** [cevio/koa-rapid-router#2]
Error: GET / 500 TypeError: Cannot read property '__MIDDLEWARES__' of undefined
    at Server.find (node_modules/koa-rapid-router/lib/server.js:41:36)
    at Koa (node_modules/koa-rapid-router/lib/server.js:26:44)
    at dispatch (node_modules/koa-compose/index.js:42:32)
    at cors (node_modules/kcors/index.js:53:14)
    at dispatch (node_modules/koa-compose/index.js:42:32)
    at dispatch (node_modules/koa-compose/index.js:42:32)
    at bodyParser (node_modules/koa-bodyparser/index.js:86:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by xiajinchun** [comment]
"kcors": "^2.2.2",
"koa": "^2.7.0",
"koa-compose":"4.1.0",
"koa-bodyparser": "^4.2.1",
"koa-jwt": "^3.5.1",
"koa-logger": "^3.2.0",
"koa-rapid-router": "^1.0.3",

**Comment by cevio** [comment]
```javascript
const target = this.features[method];
const middlewares = [...target.__MIDDLEWARES__];
```
你看下你所使用的method是什么？应该是没有注册这个method引起的。
比如说

```javascript
router.get('/abc', ...)
```
而你非要请求`Post: /abc`自然就报错了。
不过我可以在源码中提示下这个错误。

如果可以，请提供下详细的代码片段，便于我复现排查。或者你直接`npm update`看看是不是没问题。

**Comment by xiajinchun** [comment]
嗯，对，就是没找到这个路由引起的呢。
