### ISSUE TITLE
Issue with multi params

### ISSUE THREAD

**Issue by Woodu** [cevio/koa-rapid-router#6]
Set this route:
`router.get('/g/{repo:string}/{filePath?:any}', (ctx) => ..)`

Then view
`http://127.0.0.1:8080/g/xxxxxx/index.html`

Got error:
```
TypeError: Cannot read property 'index.html' of undefined
      at Server.[Server#find_children] (...node_modules/koa-rapid-router/lib/server.js:74:15)
      at Server.[Server#find_children] (...node_modules/koa-rapid-router/lib/server.js:123:37)
      at Server.[Server#find_children] (...node_modules/koa-rapid-router/lib/server.js:78:33)
      at Server.find (...node_modules/koa-rapid-router/lib/server.js:56:24)
      at Koa (...node_modules/koa-rapid-router/lib/server.js:30:44)
      at dispatch (...node_modules/koa-compose/index.js:42:32)
      at ...node_modules/koa-compress/index.js:38:11
      at dispatch (...node_modules/koa-compose/index.js:42:32)
```

At `koa-rapid-router/lib/server.js:122` print `r, l, regexp, target, reg, _params` got:
`index.html `
`524ba4a9 `
`{repo:string} `
```
{ __REGEXPS__: [ '{repo:string}' ],
  __MIDDLEWARES__: [],
  __CACHES__: Map {},
  '{repo:string}':
   { __REGEXPS__: [ '{filePath?:any}' ],
     __MIDDLEWARES__: [],
     __CACHES__: Map {},
     '{filePath?:any}':
      { __REGEXPS__: [], __MIDDLEWARES__: [Array], __CACHES__: Map {} } } } StringToRegExp {
  string: '{repo:string}',
  match_regexp: /^([a-zA-Z0-9]+)$/,
  exec_regexp: /^(.+?)$/,
  params: { repo: { index: 1, regexp: 'string', ignore: false } },
  greedy: false,
  expressions: { any: '.+', string: '[a-zA-Z0-9]+', number: '\\d+' } } 
```
`{ repo: '524ba4a9' }`

So it should be call target[regexp] instead of target[l]

**Comment by cevio** [comment]
@Woodu
fixed in https://github.com/cevio/koa-rapid-router/pull/7 
update: koa-rapid-router@1.0.9
